[package]
name = "xenon-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.14.2"
anyhow = "1.0.82"
logex = "0.1.1"
clap = { version = "4.5.4", features = ["derive"] }
serde_yml = "0.0.11"
serde = "1.0.208"